### ISSUE TITLE
Package failing on the Bioconductor devel branch

### ISSUE THREAD

**Issue by jorainer** [jhammelman/spatzie#2]
Dear package maintainer (@jhammelman ),

`spatzie` is currently failing for all platforms on the Bioconductor devel branch (build report from 2023-04-09; see [current build report](https://bioconductor.org/checkResults/3.17/bioc-LATEST/spatzie/)). Please have a look into this and fix the package.

Note that, due to the upcoming Bioconductor release, all packages should be free of errors until 2023-04-21.

thanks!

**Comment by kkrismer** [comment]
Dear Johannes,

Thanks for pointing this out!
I pushed a fix to the Bioconductor repo. I hope this resolves the issue (the [build page](https://bioconductor.org/checkResults/3.17/bioc-LATEST/spatzie/nebbiolo1-buildsrc.html) hasn't updated yet). 
Some functions (including `colMeans`) were moved from the `BiocGenerics` package to `MatrixGenerics` with the R 4.3 / BioC 3.17, which caused the issue.

Cheers,
Konstantin
